services:
  db:
    image: postgres:15
    container_name: ai-coach-todo-db
    ports:
      - "5432:5432"
    environment: # 開発用のため最低限の設定
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aicoach
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d aicoach"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: ai-coach-todo-backend
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/aicoach?schema=public"
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    restart: unless-stopped

volumes:
  postgres_data: